import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import StoreProvider from './StoreProvider';
import Navbar from './components/Layout/Navbar';
import Footer from './components/Layout/Footer';
import FadeIn from './animations/FadeIn';
import MainContainer from './components/Layout/MainContainer';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'TFPLM',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <StoreProvider>
      <html lang="en">
        <body className={inter.className}>
          <Navbar />
          <FadeIn>
            <MainContainer>{children}</MainContainer>
          </FadeIn>
          <Footer />
        </body>
      </html>
    </StoreProvider>
  );
}
